const widthAndHeight = 100;

export const letters = [
  {
    source: '/A.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter A',
    value: 'a',
  },
  {
    source: '/B.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter B',
    value: 'b',
  },
  {
    source: '/C.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter C',
    value: 'c',
  },
  {
    source: '/D.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter D',
    value: 'd',
  },
  {
    source: '/E.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter E',
    value: 'e',
  },
  {
    source: '/F.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter F',
    value: 'f',
  },
  {
    source: '/G.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter G',
    value: 'g',
  },
  {
    source: '/H.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter H',
    value: 'h',
  },
  {
    source: '/I.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter I',
    value: 'i',
  },
  {
    source: '/J.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter J',
    value: 'j',
  },
  {
    source: '/K.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter K',
    value: 'k',
  },
  {
    source: '/L.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter L',
    value: 'l',
  },
  {
    source: '/M.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter M',
    value: 'm',
  },
  {
    source: '/N.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter N',
    value: 'n',
  },

  {
    source: '/O.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter O',
    value: 'o',
  },

  {
    source: '/P.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter P',
    value: 'p',
  },
  {
    source: '/Q.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter Q',
    value: 'q',
  },
  {
    source: '/R.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter R',
    value: 'r',
  },
  {
    source: '/S.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter S',
    value: 's',
  },
  {
    source: '/T.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter T',
    value: 't',
  },
  {
    source: '/U.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter U',
    value: 'u',
  },
  {
    source: '/V.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter V',
    value: 'v',
  },
  {
    source: '/W.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter W',
    value: 'w',
  },
  {
    source: '/X.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter X',
    value: 'x',
  },
  {
    source: '/Y.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter Y',
    value: 'y',
  },
  {
    source: '/Z.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter Z',
    value: 'z',
  },
  {
    source: '/space.png',
    width: widthAndHeight,
    height: widthAndHeight,
    alt: 'letter space',
    value: ' ',
  },
];
